var namespaces_dup =
[
    [ "a1z26", "namespacea1z26.html", null ],
    [ "abbreviation", "namespaceabbreviation.html", null ],
    [ "activations", "namespaceactivations.html", null ],
    [ "atbash", "namespaceatbash.html", null ],
    [ "aystar_search", "namespaceaystar__search.html", null ],
    [ "backtracking", "namespacebacktracking.html", "namespacebacktracking" ],
    [ "base64_encoding", "namespacebase64__encoding.html", null ],
    [ "bidirectional_dijkstra", "namespacebidirectional__dijkstra.html", null ],
    [ "binomial", "namespacebinomial.html", null ],
    [ "bit_manipulation", "namespacebit__manipulation.html", [
      [ "isPowerOfTwo", "namespacebit__manipulation.html#a5032470c9974bbd6ec254bf296530a5f", null ],
      [ "next_higher_number", "namespacebit__manipulation.html#a4b76571a2a04fa99c30a96eca9997f0e", null ]
    ] ],
    [ "boruvkas_minimum_spanning_tree", "namespaceboruvkas__minimum__spanning__tree.html", null ],
    [ "caesar", "namespacecaesar.html", null ],
    [ "ciphers", "namespaceciphers.html", "namespaceciphers" ],
    [ "circular_linked_list", "namespacecircular__linked__list.html", null ],
    [ "count_bits_flip", "namespacecount__bits__flip.html", null ],
    [ "count_of_set_bits", "namespacecount__of__set__bits.html", null ],
    [ "count_of_trailing_ciphers_in_factorial_n", "namespacecount__of__trailing__ciphers__in__factorial__n.html", null ],
    [ "cut_rod", "namespacecut__rod.html", null ],
    [ "cycle_detection", "namespacecycle__detection.html", null ],
    [ "cycle_sort", "namespacecycle__sort.html", null ],
    [ "data_structures", "namespacedata__structures.html", "namespacedata__structures" ],
    [ "depth_first_search", "namespacedepth__first__search.html", null ],
    [ "disjoint_union", "namespacedisjoint__union.html", null ],
    [ "divide_and_conquer", "namespacedivide__and__conquer.html", null ],
    [ "dnf_sort", "namespacednf__sort.html", null ],
    [ "double_hashing", "namespacedouble__hashing.html", "namespacedouble__hashing" ],
    [ "dp", "namespacedp.html", null ],
    [ "dynamic_programming", "namespacedynamic__programming.html", [
      [ "is_armstrong", "namespacedynamic__programming.html#af046365a8d77a1267acc082f86135a26", null ],
      [ "LIS", "namespacedynamic__programming.html#a0a2215194e58786c34db1ccaf8031079", null ],
      [ "lps", "namespacedynamic__programming.html#afe9f45b6e30ee187509da2d1d0093412", null ],
      [ "maxCircularSum", "namespacedynamic__programming.html#a5239174fa0d987f2c67edc1f2af82beb", null ],
      [ "trappedRainwater", "namespacedynamic__programming.html#a066e0e739e7c276eee6e61d5b4d37ce8", null ]
    ] ],
    [ "false_position", "namespacefalse__position.html", null ],
    [ "fibonacci", "namespacefibonacci.html", null ],
    [ "fibonacci_sum", "namespacefibonacci__sum.html", null ],
    [ "find_non_repeating_integer", "namespacefind__non__repeating__integer.html", null ],
    [ "games", "namespacegames.html", "namespacegames" ],
    [ "gcd_of_n_numbers", "namespacegcd__of__n__numbers.html", null ],
    [ "geometric_dist", "namespacegeometric__dist.html", null ],
    [ "geometry", "namespacegeometry.html", null ],
    [ "gram_schmidt", "namespacegram__schmidt.html", null ],
    [ "graph", "namespacegraph.html", "namespacegraph" ],
    [ "graph_coloring", "namespacegraph__coloring.html", null ],
    [ "gray_code", "namespacegray__code.html", null ],
    [ "greedy_algorithms", "namespacegreedy__algorithms.html", "namespacegreedy__algorithms" ],
    [ "ground_to_ground_projectile_motion", "namespaceground__to__ground__projectile__motion.html", null ],
    [ "hamming_distance", "namespacehamming__distance.html", null ],
    [ "hashing", "namespacehashing.html", null ],
    [ "heavy_light_decomposition", "namespaceheavy__light__decomposition.html", null ],
    [ "horspool", "namespacehorspool.html", null ],
    [ "house_robber", "namespacehouse__robber.html", null ],
    [ "inorder_successor_of_bst", "namespaceinorder__successor__of__bst.html", null ],
    [ "interpolation_search", "namespaceinterpolation__search.html", null ],
    [ "inversion", "namespaceinversion.html", null ],
    [ "is_graph_bipartite", "namespaceis__graph__bipartite.html", null ],
    [ "iterative_tree_traversals", "namespaceiterative__tree__traversals.html", null ],
    [ "jarvis", "namespacejarvis.html", null ],
    [ "k_nearest_neighbors", "namespacek__nearest__neighbors.html", null ],
    [ "kadane", "namespacekadane.html", null ],
    [ "karatsuba_algorithm", "namespacekaratsuba__algorithm.html", null ],
    [ "Knapsack", "namespace_knapsack.html", null ],
    [ "knight_tour", "namespaceknight__tour.html", null ],
    [ "layers", "namespacelayers.html", null ],
    [ "linear_probing", "namespacelinear__probing.html", "namespacelinear__probing" ],
    [ "linear_recurrence_matrix", "namespacelinear__recurrence__matrix.html", null ],
    [ "linked_list", "namespacelinked__list.html", null ],
    [ "list_array", "namespacelist__array.html", null ],
    [ "lru_cache", "namespacelru__cache.html", null ],
    [ "machine_learning", "namespacemachine__learning.html", "namespacemachine__learning" ],
    [ "magic_sequence", "namespacemagic__sequence.html", null ],
    [ "manacher", "namespacemanacher.html", null ],
    [ "math", "namespacemath.html", "namespacemath" ],
    [ "MD5", "namespace_m_d5.html", null ],
    [ "median_search", "namespacemedian__search.html", null ],
    [ "merge_insertion", "namespacemerge__insertion.html", null ],
    [ "midpoint_rule", "namespacemidpoint__rule.html", null ],
    [ "mincoins_topdown", "namespacemincoins__topdown.html", null ],
    [ "Minimum", "namespace_minimum.html", null ],
    [ "modular_division", "namespacemodular__division.html", null ],
    [ "monte_carlo", "namespacemonte__carlo.html", null ],
    [ "morse", "namespacemorse.html", null ],
    [ "n_bonacci", "namespacen__bonacci.html", null ],
    [ "n_queens", "namespacen__queens.html", null ],
    [ "n_queens_all_solutions", "namespacen__queens__all__solutions.html", null ],
    [ "n_queens_optimized", "namespacen__queens__optimized.html", null ],
    [ "ncr_modulo_p", "namespacencr__modulo__p.html", null ],
    [ "neural_network", "namespaceneural__network.html", null ],
    [ "numerical_methods", "namespacenumerical__methods.html", [
      [ "babylonian_method", "namespacenumerical__methods.html#a28e67885f8606564cc8335f483f63309", null ],
      [ "FastFourierTransform", "namespacenumerical__methods.html#a158fd271b9a53e8f3f60b08b18857150", null ],
      [ "InverseFastFourierTransform", "namespacenumerical__methods.html#aee56dc85997b8cd42bad71a5d6bd2d93", null ]
    ] ],
    [ "operations_on_datastructures", "namespaceoperations__on__datastructures.html", "namespaceoperations__on__datastructures" ],
    [ "others", "namespaceothers.html", "namespaceothers" ],
    [ "palindrome_partitioning", "namespacepalindrome__partitioning.html", null ],
    [ "pancake_sort", "namespacepancake__sort.html", null ],
    [ "physics", "namespacephysics.html", null ],
    [ "postfix_expression", "namespacepostfix__expression.html", null ],
    [ "prefix_sum_array", "namespaceprefix__sum__array.html", null ],
    [ "probability", "namespaceprobability.html", null ],
    [ "qr_algorithm", "namespaceqr__algorithm.html", [
      [ "eigen_values", "namespaceqr__algorithm.html#a28e2fa3e803abaea6c568dc45d69d8cc", null ],
      [ "operator<<", "namespaceqr__algorithm.html#adfbdf47277c8cfee229b05b72f1f7834", null ],
      [ "operator<<", "namespaceqr__algorithm.html#a257425cb2365359da51c6fe6741834d8", null ],
      [ "qr_decompose", "namespaceqr__algorithm.html#a73ce637634fc49e1d10d190eb388ebf1", null ],
      [ "vector_dot", "namespaceqr__algorithm.html#a8ea313a1a1b5f9d0e3e332c29c6446ec", null ],
      [ "vector_mag", "namespaceqr__algorithm.html#ad16da2183db22378435042f26af43d5f", null ],
      [ "vector_proj", "namespaceqr__algorithm.html#a6d3c7dce1f142141f509d09f6c0e25dc", null ]
    ] ],
    [ "quadratic_probing", "namespacequadratic__probing.html", "namespacequadratic__probing" ],
    [ "queue_using_array", "namespacequeue__using__array.html", null ],
    [ "quick_sort", "namespacequick__sort.html", null ],
    [ "radix_sort", "namespaceradix__sort.html", null ],
    [ "random_pivot_quick_sort", "namespacerandom__pivot__quick__sort.html", null ],
    [ "range_queries", "namespacerange__queries.html", "namespacerange__queries" ],
    [ "rat_maze", "namespacerat__maze.html", null ],
    [ "reverse_binary_tree", "namespacereverse__binary__tree.html", null ],
    [ "runge_kutta", "namespacerunge__kutta.html", null ],
    [ "saddleback", "namespacesaddleback.html", null ],
    [ "search", "namespacesearch.html", null ],
    [ "selection_sort_recursive", "namespaceselection__sort__recursive.html", null ],
    [ "setKthBit", "namespaceset_kth_bit.html", null ],
    [ "SHA", "namespace_s_h_a.html", null ],
    [ "shortest_common_supersequence", "namespaceshortest__common__supersequence.html", null ],
    [ "simpson_method", "namespacesimpson__method.html", null ],
    [ "sorting", "namespacesorting.html", [
      [ "binary_search", "namespacesorting.html#a034d8b276518a902962e87d3158b64fd", null ],
      [ "gnomeSort", "namespacesorting.html#aa3677f87b5b4756bc77e9e34c5f27935", null ],
      [ "gnomeSort", "namespacesorting.html#a2f8bc626eb57acae24a94636a23af6a1", null ],
      [ "insertionSort", "namespacesorting.html#a8fe6bac9e03f58abcc2ce26ef3de1b5f", null ],
      [ "insertionSort", "namespacesorting.html#a78cb2f3b97b6db2c062b2a1df05c9ea9", null ],
      [ "insertionSort_binsrch", "namespacesorting.html#a5f4bc75cca6dd8294af2d0e328006c68", null ],
      [ "iterativeQuickSort", "namespacesorting.html#a263595fd9a0163b5b997b89fab3a0dc5", null ],
      [ "merge", "namespacesorting.html#aa26de383227859210f14dcf12201a079", null ],
      [ "non_recursive_merge_sort", "namespacesorting.html#ae97f4dd815654c4682f564afd718e824", null ],
      [ "non_recursive_merge_sort", "namespacesorting.html#a140d913e42fb94176a0b2c8b29a80420", null ],
      [ "non_recursive_merge_sort", "namespacesorting.html#a27236b8d3df3832e1f1225576a122534", null ],
      [ "partition", "namespacesorting.html#aac8f44b28b4aa96444383030b28f8b34", null ],
      [ "pigeonSort", "namespacesorting.html#a0e9e1b21a1684585e9e50f9afe4d53a3", null ],
      [ "quicksort", "namespacesorting.html#a9f59fe72dacc1f1218ef3c303d843168", null ],
      [ "quicksort", "namespacesorting.html#a6eb67c2f91c98cf4464f75b5882022de", null ],
      [ "randomized_bogosort", "namespacesorting.html#affc6ee160142cd017f8c4b213437d0fd", null ],
      [ "recursive_bubble_sort", "namespacesorting.html#ae3a775d99dbbb94c130a973df0cfddcf", null ],
      [ "shell_sort", "namespacesorting.html#af2c5b92cbfe73f63f6074c61b0a45331", null ],
      [ "shell_sort", "namespacesorting.html#a5669396c6a6b1e14b97589b6e37980aa", null ],
      [ "shell_sort", "namespacesorting.html#a4d76603c54d3dc56146e92d10a043924", null ],
      [ "shuffle", "namespacesorting.html#a7bfe11bd4703eacd1dab93f25ec639c5", null ]
    ] ],
    [ "sparse_table", "namespacesparse__table.html", null ],
    [ "spirograph", "namespacespirograph.html", [
      [ "spirograph", "namespacespirograph.html#aeca22dbe4563358960e907a40cd3e1ac", null ],
      [ "test", "namespacespirograph.html#a8e83a64e8443fff1e5ffdc1c299c1e99", null ]
    ] ],
    [ "stack_using_queue", "namespacestack__using__queue.html", null ],
    [ "statistics", "namespacestatistics.html", "namespacestatistics" ],
    [ "strand", "namespacestrand.html", null ],
    [ "strassens_multiplication", "namespacestrassens__multiplication.html", null ],
    [ "string", "namespacestring.html", [
      [ "duval", "namespacestring.html#ac2a35302e6bed93c4b2c6f55a21a5632", null ]
    ] ],
    [ "string_search", "namespacestring__search.html", [
      [ "brute_force", "namespacestring__search.html#aeb2cd81064717aedd62bfb096b1a73d8", null ],
      [ "check_if_equal", "namespacestring__search.html#aebe07cea289a13142503d98be7df11fd", null ],
      [ "create_hash", "namespacestring__search.html#a8fb0bc932ba8b582c9f4c71338d050f8", null ],
      [ "getFailureArray", "namespacestring__search.html#a83c72ff237cdf623e42d4295e0029bf9", null ],
      [ "kmp", "namespacestring__search.html#a1e37af2f023495129cb57338c801209e", null ],
      [ "rabin_karp", "namespacestring__search.html#a21c673d56cbf67b1d2ee4d869185b7d9", null ],
      [ "recalculate_hash", "namespacestring__search.html#aed769d565b705a9b3e0eb1ec74088893", null ]
    ] ],
    [ "strings", "namespacestrings.html", "namespacestrings" ],
    [ "subarray_sum", "namespacesubarray__sum.html", null ],
    [ "sublist_search", "namespacesublist__search.html", null ],
    [ "subset_sum", "namespacesubset__sum.html", null ],
    [ "Subsets", "namespace_subsets.html", null ],
    [ "sudoku_solver", "namespacesudoku__solver.html", null ],
    [ "tests", "namespacetests.html", [
      [ "test1", "namespacetests.html#a167c24bd817469ae47358d12e034f2d5", null ],
      [ "test2", "namespacetests.html#abdd77344d4af8fd56d14a5cabbf2f669", null ],
      [ "test3", "namespacetests.html#aa515639572647508b94986489aab6d76", null ],
      [ "test4", "namespacetests.html#a2b9769e44683dcb67fe1083ad91e134d", null ],
      [ "test5", "namespacetests.html#af7b81d7a1534216af6a36a80135beb86", null ],
      [ "test6", "namespacetests.html#aacafde185abd8670abee51157f273dc2", null ]
    ] ],
    [ "travellingSalesman_bitmanipulation", "namespacetravelling_salesman__bitmanipulation.html", null ],
    [ "tree_234", "namespacetree__234.html", null ],
    [ "trie_operations", "namespacetrie__operations.html", null ],
    [ "trie_using_hashmap", "namespacetrie__using__hashmap.html", null ],
    [ "util_functions", "namespaceutil__functions.html", null ],
    [ "utils", "namespaceutils.html", null ],
    [ "vector_cross", "namespacevector__cross.html", null ],
    [ "vigenere", "namespacevigenere.html", null ],
    [ "wave_sort", "namespacewave__sort.html", null ],
    [ "wiggle_sort", "namespacewiggle__sort.html", null ],
    [ "wildcard_matching", "namespacewildcard__matching.html", null ],
    [ "windowed_median", "namespacewindowed__median.html", null ],
    [ "word_break", "namespaceword__break.html", null ],
    [ "XOR", "namespace_x_o_r.html", null ]
];